egutter:
  twitter: egutter
  github: egutter
  full_name: Emilio Gutter
  company: 10Pines
  title: The Agile City Building Game
  abstract: |
    ¿Estás listo para construir tu propia ciudad? Unite a un equipo de construcción, tomá tus
    herramientas y preparate para construir tu fantástica ciudad mientras aprendés los principios
    fundamentales del desarrollo Lean de software. ¡Vos y tu equipo van a maximizar el valor entregado
    a la gente de la ciudad mientras compiten con los otros equipos para mostrar quien es el mejor
    equipo de construcción ágil! El objetivo del juego es permitirte experimentar los principios
    fundamentales del desarrollo Ágil/Lean de software mientras te divertís y aprendés con tus
    compañeros. Durante el juego, cada equipo tendrá que bocetar edificios y objetos en la ciudad,
    usando materiales simples provistos por los organizadores. Los equipos van a recibir un story
    backlog, cada uno con un valor de negocio asignado. Cada equipo va a llevar adelante las
    historias dentro de cortas iteraciones para maximizar el valor entregado al final del juego.
  bio: |
    Emilio es uno de los fundadores de 10Pines. Trabajó en el área de desarrollo de software por
    más de 10 años, participando en variados proyectos para Argentina, Brasil, Reino Unido, Estados
    Unidos, Francia, Rumania y Bulgaria. Ocupó puestos de desarrollador, líder de proyecto y coach
    agile con experiencia en diferentes industrias como servicios de crédito, medios y entretenimiento,
    publicidad, turismo entre otras. También está fuertemente comprometido con la comunidad Agile
    local y es un miembro del equipo organizador de las conferencias latinoamericanas "Agiles" desde
    2008, siendo en Agiles 2012 uno de los organizadores principales.

martinsalias:
  twitter: martinsalias
  github: martinsalias
  full_name: Martín Salias
  company: Kleer
  title: Yoseki Coding Dojo
  abstract: |
    El Dojo es, en la tradición japonesa, el lugar destinado a la enseñanza y el perfeccionamiento
    en las artes marciales y la meditación. Yoseki es donde se localizan los auxiliares del maestro
    y aquellos estudiantes avanzados. Es donde todo aprendiz quiere llegar. La iniciativa del
    Coding Dojo se está difundiendo rápidamente en muchas ciudades del mundo. Su filosofía se trata
    de aprender, aprender y aprender. En nuestro Coding Dojo nos reunimos para resolver Coding
    Katas (ejercicios de programación) trabajando de a pares (y rotando con diferentes patrones)
    y basando la práctica en TDD.
  bio: |
    Martín lleva 30 años dedicado a la construcción de software y ha trabajado en proyectos a lo
    largo y ancho de América, Australia y Europa, para organizaciones tan variadas como las Naciones Unidas
    o Microsoft Corp. Ha desarrollado en diversas plataformas y lenguajes como C++, Fox, Java,
    COBOL, .NET, Python, Ruby y otros. Es uno de los Trainers y Coaches en Kleer, una organización
    latinoamericana dedicada a difundir mejores prácticas organizacionales relacionadas a la
    construcción de software y otros productos basados en innovación en equipos.

dariocravero:
  twitter: dariocravero
  github: dariocravero
  full_name: Darío Javier Cravero
  company: UXtemple
  title: Understanding deployments
  abstract: |
    Este taller consiste en raspar la superficie y sumergirse en profundidad en cómo hacer deploy
    a producción de tus aplicaciones. Saber cómo funcionan las cosas es el primer paso en pos de
    entender qué salió mal cuando tu plataforma explotó a las cuatro de la mañana de ese loco
    sábado. El entorno de deploy es la casa de tu plataforma y el dueño debería saber cómo
    construirla desde los cimientos y mantenerla limpia y ordenada para que los inquilinos
    vivan felices por siempre :).
  bio: |
    CTO en UXtemple. Padrino core mantainer. Amante del yoga y bebedor de mate.

damianmarti:
  twitter: damianmarti
  github: damianmarti
  full_name: Damián Martinelli
  company: Sumavisos
  title: Introducción a NoSQL
  abstract: |
    El taller consiste en una introducción a los diferentes tipos de base de datos no relacionales,
    como ser clave/valor, por columnas, de documentos y de grafos. Contando las caracteristicas
    principales de cada una, cuándo es útil, cuándo no, y ejemplos de motores de base de datos
    disponibles para cada tipo.
    Cada vez se habla más de NoSQL y cada vez se utilizan más base de datos de este tipo, pero hay
    muchos programadores que todavia no las conocen o solo la conocen de oído, sin conocer qué es
    cada una y cuando es útil utilizarlas.
  bio: |
    Damián es Ingeniero en Informática recibido en la UBA. Programa desde el GWBasic y está en el
    mundo de la programación web desde hace alrededor de 15 años. Programó en Pascal, Delphi,
    C, Java, PHP, pero cuando se metió en el mundo Ruby de la mano de Rails allá por el 2006,
    nunca más quiso tocar otro lenguaje. Es uno de los fundadores y CTO de Sumavisos, un buscador
    de avisos clasificados presente en 30 países.

tutec:
  twitter: tutec
  github: tute
  full_name: Tute Costa
  company: General Assembly
  title: 'Simplificando código: de monstruo a elegante en tres simples pasos!'
  abstract: |
    Todos tenemos algún muerto en placard, propio o de nuestro equipo. En este taller aprenderemos 
    cómo modificar código difícil de entender y altamente acoplado, mostrando cómo transformarlo 
    siguiendo y tendiendo a patrones, para resultar en un bello unicornio que cumple con las
    <a href="http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers" 
    target="_blank"> cuatro reglas de Sandi Metz</a>, sin grandes dolores de cabeza, sin cambiar 
    todo de una vez deteniendo la productividad, y, por supuesto, divirtiéndonos.
  bio: |
    Tute mantiene los proyectos <a href="https://github.com/tute/merit" target="_blank">merit</a> y
    <a href="https://github.com/applicake/doorkeeper" target="_blank">doorkeeper</a>. También hizo una aplicación
    para saber dónde está y qué lo rodea: <a href="http://dynamicatlas.herokuapp.com/" target="_blank">
    dynamicatlas</a>. Trabaja en <a href="https://generalassemb.ly/">General Assembly</a>.

luke_ar:
  twitter: luke_ar
  github: delucas
  full_name: Lucas Videla
  company: Uno21
  title: "Aún no usas Git y GitHub?"
  abstract: |
    Un taller en el que los asistentes experimentarán las bases y primeros pasos con la principal
    herramienta de control de versiones de la actualidad. Como todo taller, la consigna será "manos a la
    obra", por lo que seguiremos algunas consignas que nos llevarán a vivir el uso de git. Traé tu
    computadora, llevate git puesto.
  bio: |
    Lucas es un aprendiz incansable del arte del desarrollo de software. Dicta clases en dos universidades, y es
    el encargado de enseñar las bases de la programación a jóvenes de 17 a 6x años (porque aún no llegó
    nadie más grande). Actualmente trabaja para <a href="http://www.uno21.com.ar" target="_blank">uno21</a>
    y es cofundador del movimiento <a href="http://www.wecode.io" target="_blank">wecode</a>. Algunos de
    sus proyectos son <a href="http://braid.herokuapp.com" target="_blank">braid</a> y
    <a href="https://github.com/delucas/notas" target="_blank">notas</a>.

luke_ar2:
  twitter: luke_ar
  github: delucas
  full_name: Lucas Videla
  company: Uno21
  title: 'Test Driven Development In Real Life'
  abstract: |
    Es un taller para experimentar junto a los asistentes el uso y
    esencia de TDD en Ruby. Vamos a hacer un ejemplo juntos, y luego lo harán crecer viendo la potencia de
    tener la seguridad que los tests proporcionan. Está pensado para gente que domine el lenguaje, aunque no conozca las herramientas de testing.
    Si no conocés la técnica de TDD, o si la viste sólo en la facultad o algunos videos, te propongo que
    vengas a hacerlo en un proyecto de verdad.
  bio: |
    Lucas es un aprendiz incansable del arte del desarrollo de software. Dicta clases en dos universidades, y es
    el encargado de enseñar las bases de la programación a jóvenes de 17 a 6x años (porque aún no llegó
    nadie más grande). Actualmente trabaja para <a href="http://www.uno21.com.ar" target="_blank">uno21</a>
    y es cofundador del movimiento <a href="http://www.wecode.io" target="_blank">wecode</a>. Algunos de
    sus proyectos son <a href="http://braid.herokuapp.com" target="_blank">braid</a> y
    <a href="https://github.com/delucas/notas" target="_blank">notas</a>.
  hidden: true

frodsan:
  twitter: frodsan
  github: frodsan
  full_name: Francesco Rodriguez
  company: ''
  title: 'Introducción a Cuba (The Ruby Microframework)'
  abstract: |
    En este taller aprenderás como crear aplicaciones web con Cuba, el microframework hecho en Ruby. El taller 
    está diseñado para principiantes que quieran empezar una aplicación Cuba desde cero. No asume alguna 
    experiencia previa con otros frameworks web, sin embargo para sacarle el máximo provecho deberás conocer 
    algo sobre Ruby (<a href="http://tryruby.org/" target="_blank">http://tryruby.org/</a>).
  bio: |
    Francesco contribuye activamente a proyectos Open Source como Rails, Rubinius y Ember.js. Además es autor 
    de varias librerías en Ruby.

joaquinvicente:
  twitter: joaquinvicente
  github: llopez
  full_name: Joaquín Vicente & Luis López
  company: Altoros
  title: 'Introducción a Ruby on Rails'
  abstract: |
    En este taller aprenderás como crear aplicaciones web con el framework Rails. El taller está dirigido a 
    programadores que aún no tengan experiencia en Ruby, y puedan hacer una pequeña aplicación durante el 
    taller. 
  bio: |
    Luis a.k.a 'luigibyte' es programador e inline skater. Llegó al mundo de la programación de la mano de 
    Ruby y desde entonces no ha prestado mucha atención a otros lenguajes.
    A lo largo de su carrera se ha encontrado con mucha y muy buena gente que le ha enseñado y entiende que 
    este taller es una buena oportunidad de devolver algo de todo eso.
    Dicen que el último paso para comprender algo es poder enseñarlo y ése es su objetivo.
    <br/><br/>
    Joaquín aprendió de chico a programar en Basic para poder hackear el juego de la viborita del DOS. Desde 
    entonces se dio cuenta que la programación era lo suyo. Recorrió una larga variedad de lenguajes hasta 
    que conoció Ruby. Dice que fue amor a primera vista. Le gusta aprender y enseñar cosas nuevas todo el 
    tiempo. Cuando no programa le encanta viajar, aunque cada tanto extraña Buenos Aires. Sueña con 
    llevar su "oficina" en una casa rodante alrededor del mundo.
