egutter:
  twitter: egutter
  github: egutter
  full_name: Emilio Gutter
  company: 10Pines
  title: The Agile City Building Game
  abstract: |
    Are you ready to start building your own city? Join a construction team, take your tools and
    get ready to build a fantastic city while you learn fundamental principles of Lean software
    development. You an your team will have to maximize value delivered to the people in your
    city while you compete with other teams to show which is the best agile building team! The
    objective of this game is to let you experience the fundamental principles behind Lean/Agile
    software development while you have fun and learn with your partners. During the game, each
    team will have to mockup buildings and objects in the city, using simple materials provided
    by the organizers. Teams will get a story backlog, each one with an assigned business value.
    Each team will carry out the stories within short iterations in order to maximize the value
    delivered by the end of the game.
  bio: |
    Emilio is one of 10Pines co-founders. He has been working in software development area for more
    than 10 years, participating in several projects for Argentina, Brazil, United Kingdom, United
    States, France, Romania and Bulgaria. He has performed as software developer, project leader
    and agile coach with experience in different industries such as credit services, media &
    entertainment, advertising, travel & leisure among others. Also, he is strongly committed
    with the local Agile community and he is a member of the organization team of the Latin
    American "Agiles" conference since 2008, being in Agiles 2012 the conference co-chair.

martinsalias:
  twitter: martinsalias
  github: martinsalias
  full_name: Martín Salias
  company: Kleer
  title: Yoseki Coding Dojo
  abstract: |
    The Dojo is, in japanese tradition, the place intended for teaching and perfecting martial
    arts and meditation. Yoseki is where the assistants of the teacher and advanced students
    stay. It's where every apprentice wants to be. The Coding Dojo initiative is spreading
    rapidly in many cities around the world. Its philosophy is about learning, learning and
    learning. In our Coding Dojo we meet to solve Coding Katas (programming exercises) working
    in pairs (and rotating in different ways) and using TDD.
  bio: |
    Martín has dedicated 30 years to software construction and has worked in projects through all
    America, Australia and Europe, for organizations as varied as the United Nations or Microsoft
    Corp. He has developed in different platforms and languajes such as C++, Fox, Java, COBOL,
    .NET, Python, Ruby and others. He is one of the Trainers and Coaches from Kleer, a latinoamerican
    organization devoted to spreading the organizational best practices related to software
    building and other products based on team innovation.

dariocravero:
  twitter: dariocravero
  github: dariocravero
  full_name: Darío Javier Cravero
  company: UXtemple
  title: Understanding deployments
  abstract: |
    This workshop is a hands on, scratch the surface and dive deep into how to deploy your
    applications into production. Knowing how things work is the first step towards understanding
    what went wrong when your platform blew up at four in the morning that crazy Saturday. The
    deployment environment is your platform's home and as its landlord you should know how to build
    it from the ground up and keep it nice and tidy so that the tenants live happily ever after :).
  bio: |
    CTO @ UXtemple. Padrino core mantainer. Yoga lover and mate drinker.

damianmarti:
  twitter: damianmarti
  github: damianmarti
  full_name: Damián Martinelli
  company: Sumavisos
  title: Introducción a NoSQL
  abstract: |
    This workshop is an introduction to the different types of non-relational databases, like
    key-value, columns, documents and graphs. Explaining the main aspects of each one, when they
    are useful (and when they aren't,) and examples of different engines of each type.
    NoSQL is a rising topic and so is their usage, but many programmers still don't know them
    or just heard something about it, without knowing what they are or when they are useful.
  bio: |
    Damián is a Software Engineer graduated from UBA. He programmed since the GWBasic era and
    he entered the web programming world 15 years ago. He coded in Pascal, Delphi, C, Java,
    PHP, but when he entered the Ruby world through Rails by 2006, never wanted to switch
    to another language again. He is one of the founders and CTO of Sumavisos, a classified ads search
    engine available in 30 countries.

tutec:
  twitter: tutec
  github: tute
  full_name: Tute Costa
  company: General Assembly
  title: 'Simplifying your code: from monster to elegant in three simple steps!'
  abstract: |
    We all have skeletons in our closet, ours or from our team. In this workshop we'll learn how 
    to modify hard to understand, highly coupled code, to transform it following and tending to 
    patterns, so it becomes a beautiful unicorn which complies with Sandi Metz's <a 
    href="http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers" target="_blank">
    four rules</a>, avoiding headaches, without "big bang refactors", and, of course, having fun.
  bio: |
    Tute maintains the projects: <a href="https://github.com/tute/merit" target="_blank">merit</a> and
    <a href="https://github.com/applicake/doorkeeper" target="_blank">doorkeeper</a>. He created an
    app to know where he is and what's around: <a href="http://dynamicatlas.herokuapp.com/" target="_blank">
    dynamicatlas</a>. He works at <a href="https://generalassemb.ly/">General Assembly</a>.

luke_ar:
  twitter: luke_ar
  github: delucas
  full_name: Lucas Videla
  company: Uno21
  title: "TDD IRL // Don't you use git and GitHub yet?"
  abstract: |
    "Test Driven Development In Real Life" is a workshop for attendees to experience the use and essence of
    TDD in Ruby. We'll develop an example together, and see the power of growing software with the security
    that tests provide us. It is designed for people who have learnt the language, but do not necessarily
    know the testing tools.
    If you don't know the technique of TDD, or if you saw it only at University or some fancy videos, we
    suggest you to come and do it in a real project.
    //
    Don't you use git and GitHub yet?
    A workshop in which participants will experience the basics and first steps with the main version
    control system today. Like any workshop, the slogan will be "hands-on", and we will continue some
    instructions that will drive us to live the use of git. Bring your computer, get on with git.
  bio: |
    Lucas is a tireless apprentice of the art of programming. He lectures at two universities, and teaches
    the basics of programming for young people from age 17 to 6x (because nobody older attended yet).
    He currently works at <a href="http://www.uno21.com.ar" target="_blank">uno21</a> and is one of the
    <a href = "http://www.wecode.io "target ="_blank">wecode</a> movement co-founders. Some of his projects
    are <a href="braid.herokuapp.com" target="_blank">braid</a> and
    <a href="github.com/delucas/notas" target="_blank">notas</a>.

frodsan:
  twitter: frodsan
  github: frodsan
  full_name: Francesco Rodriguez
  company: ''
  title: 'Introduction to Cuba (The Ruby Microframework)'
  abstract: |
    In this workshop you will learn to build web applications with Cuba, a microframework made on Ruby. The 
    workshop is intended for beginners that want to build an application with Cuba from the beginning. 
    Experience with other web frameworks won't be required. However, you should know a little about Ruby. 
    For example you can check out <a href="http://tryruby.org/" target="_blank">http://tryruby.org/</a>.
  bio: |
    Francesco actively contributes to Open Source projects like Rails, Rubinius and Ember.js. He is also 
    the author of several Ruby libraries.


joaquinvicente:
  twitter: joaquinvicente
  github: llopez
  full_name: Joaquín Vicente & Luis López
  company: Altoros
  title: 'Introduction to Ruby on Rails'
  abstract: |
    In this workshop you'll learn how to create web applications with Rails. The workshop is for programmers 
    of any other technology, that still don't have experience in Ruby. The objective is for everyone to 
    build a small application during the workshop.
  bio: |
    Luis a.k.a 'luigibyte' is a programmer and inline skater. He came to the programming world because of 
    Ruby and since then he has focused on this language.
    Since his start in the field, he encountered some nice people that teached him, so he sees this workshop 
    as an opportunity of giving up some of this.
    They say that the last step to understand something is to teach it, so that's his goal.
    <br/><br/>
    Joaquín learnt to code when he was a child and wanted to hack the snake game in Basic that ran under DOS.
    Since then he realised that programming was his thing. He came across a large variety of languages until 
    he met Ruby. He says that it was love at first sight. He likes to learn and teach new things all the time. 
    When he is not programming, he loves to travel, but he misses Buenos Aires from time to time. He dreams 
    to take his "office" on a RV across the world.
