site_lang: es
nav_home: Inicio
nav_speakers: Oradores
nav_program: Programa
nav_rfd: Ruby Fun Day
nav_venue: Lugar
nav_sponsors: Sponsors
nav_lang_selector_url: /en
nav_lang_selector_message: Do you speak English?
date: 27 y 28 de Noviembre, 2013
header: |
  Con orgullo anunciamos la tercera edición de RubyConf Argentina,<br>
  una conferencia regional sobre Ruby y tecnologías relacionadas.
register: ¡Registrate ahora!
price_legend: (aprox. USD 120), sólo por esta semana!
ticket_includes: |
  Tu entrada incluye: Acceso a todas las charlas durante los dos días de conferencia,
  desayunos, almuerzos y coffee breaks, camiseta oficial de la conferencia, acceso al Ruby Fun Day
cfp_title: Oradores
cfp_text: ¡Pronto anunciaremos la lista completa...!
cfp_link: ¡Envianos tu propuesta antes del 13 de septiembre!
venue_title: Lugar
venue_text: Este año el evento vuelve a
sponsors_title: Sponsors
sponsors_text: ¡Los Rubyistas amamos a las organizaciones que apoyan a la comunidad!
contact_us: Envianos un email
sponsors_text_closure: y te contaremos cómo tu empresa puede aprovechar esta gran oportunidad.
footer_first: RubyConf Argentina es organizada por
footer_end: una asociación sin fines de lucro dedicada a promover el crecimiento de Ruby y tecnologías relacionadas
past_editions: Eventos anteriores
program_title: Programa de las Charlas
tba: Pronto publicaremos información sobre su charla...
rfd_title: Programa de Talleres
rfd_description: |
  <p>Un día completo para aprender, conocer y divertirse con Ruby y su increíble comunidad! Y una oportunidad fantástica para conocer a otros colegas y compartir experiencias.</p>
  <p>Las actividades están pensadas para que cada uno traiga su laptop, o se junte con aquellos que la traigan, para poder hacer los juegos y talleres. Habrá wi-fi para todos.</p>
  <p>La agenda ha sido separada en tracks simultáneos en función del nivel de experiencia de la audiencia.</p>
  <p>Las sesiones serán en el idioma elegido por sus respectivos oradores. Lo sentimos, pero no habrá servicio de traducción durante el Ruby Fun Day.</p>
admission_disclaimer: | 
  La organización del evento se reserva el derecho de admisión y permanencia conforme con lo 
  establecido en la legislación vigente.