site_lang: en
nav_home: Home
nav_speakers: Speakers
nav_program: Program
nav_schedule: Schedule
nav_rfd: Ruby Fun Day
nav_venue: Venue
nav_sponsors: Sponsors
nav_lang_selector_url: /es
nav_lang_selector_message: ¿Hablas español?
date: November 27 &amp; 28, 2013
header: |
  We are very proud to announce the third edition of RubyConf Argentina,<br>
  a regional conference about Ruby and related technologies.
register: Register now!
register_rfd: Register for free!
price_legend: (USD 135)
ticket_includes: |
  Your ticket includes: access to all sessions during the conference, breakfasts, lunches and coffee breaks, official T-shirt, access to Ruby Fun Day
cfp_title: Speakers
cfp_text: More to be announced soon...!
cfp_link: Send your proposal before September 13th!
venue_title: Venue
venue_text: This year the event returns to
sponsors_title: Sponsors
sponsors_text: Rubyists love those companies that support the community!
contact_us: Email us
sponsors_text_closure: to discuss how your company can be part of this great opportunity.
footer_first: RubyConf Argentina is organized by
footer_end: a non-profit organization dedicated to promoting the growth of Ruby and related technologies
past_editions: Past events
program_title: Conference Program
tba: More information about this presentation coming soon...
rfd_title: Workshops Program
rfd_description: |
  <p>A whole day to learn, meet and have fun with Ruby and its great community!w And a fantastic opportunity for you to meet other peers and share experiences.</p>
  <p>Activities are meant for you to practice what you're learning with your own laptop, or join someone else who brought his/her. There will be wi-fi for everyone.</p>
  <p>The agenda is organized into tracks based on the audience ruby experience.</p>
  <p>The sessions will be in the language chosen by their respective speakers. Sorry, but translation services will not be available during Ruby Fun Day.</p>
admission_disclaimer: | 
  The event organizers reserve the right to refuse admission or expell any participant engaging in 
  incorrect behavior in accordance with the provisions of law.
schedule_title: Schedule
schedule_title_rfd: Tuesday, November 26th - <a href="rfd.html">Ruby Fun Day</a>
schedule_title_day1: Wednesday, November 27th
schedule_title_day2: Thursday, November 28th
welcome: Welcome
registration: Registration
breakfast: Registration and Breakfast
lunch: Lunch
break: Break
schedule_disclaimer: Schedule is subject to change because of organization matters.
