site_lang: en
nav_home: Home
nav_speakers: Speakers
nav_program: Program
nav_rfd: Ruby Fun Day
nav_venue: Venue
nav_sponsors: Sponsors
nav_lang_selector_url: /es
nav_lang_selector_message: ¿Hablas español?
date: November 27 &amp; 28, 2013
header: |
  We are very proud to announce the third edition of RubyConf Argentina,<br>
  a regional conference about Ruby and related technologies.
register: Register now!
price_legend: (about USD 88), upto October 11th
ticket_includes: |
  Your ticket includes: access to all sessions during the conference, breakfasts, lunches and coffee breaks, official T-shirt, access to Ruby Fun Day
cfp_title: Speakers
cfp_text: More to be announced soon...!
cfp_link: Send your proposal before September 13th!
venue_title: Venue
venue_text: This year the event returns to
sponsors_title: Sponsors
sponsors_text: Rubyists love those companies that support the community!
contact_us: Email us
sponsors_text_closure: to discuss how your company can be part of this great opportunity.
footer_first: RubyConf Argentina is organized by
footer_end: a non-profit organization dedicated to promoting the growth of Ruby and related technologies
past_editions: Past events
program_title: Conference Program
tba: More information about this presentation coming soon...
rfd_title: Ruby Fun Day (Workshops)
